# # Generated by Django 5.0.6 on 2024-06-13 19:07
#
# from django.db import migrations, models
#
#
# class Migration(migrations.Migration):
#
#     initial = True
#
#     dependencies = [
#     ]
#
#     operations = [
#         migrations.CreateModel(
#             name='Series',
#             fields=[
#                 ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('name', models.CharField(max_length=1000)),
#                 ('description',models.CharField(max_length=100000)),
#             ],
#         ),
#     ]
# main/migrations/0001_initial.py
#
# from django.db import migrations, models
#
# class Migration(migrations.Migration):
#
#     initial = True
#
#     dependencies = []
#
#     operations = [
#         migrations.CreateModel(
#             name='SeriesList',
#             fields=[
#                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('name', models.CharField(max_length=100)),
#             ],
#         ),
#     ]
# main/migrations/0001_initial.py

# from django.db import migrations, models
#
# class Migration(migrations.Migration):
#
#     initial = True
#
#     dependencies = []
#
#     operations = [
#         migrations.CreateModel(
#             name='SeriesList',
#             fields=[
#                 ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
#                 ('name', models.CharField(max_length=100)),
#             ],
#         ),
#     ]
# Generated by Django 5.0.6 on 2024-06-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SERIES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(max_length=1000000)),
            ],
        ),
    ]
