# Generated by Django 5.0.6 on 2024-06-13 19:23
# from django.db import migrations
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ('main', '0001_initial'),
#     ]
#
#     operations = [
#         migrations.RenameModel(
#             old_name='SeriesList',  # Ensure this matches the model name in 0001_initial.py
#             new_name='NewSeriesListName',  # Change to your desired new model name
#         ),
#     ]
#
# from django.db import migrations
#
#
# class Migration(migrations.Migration):
#
#     dependencies = [
#         ('main', '0001_initial'),
#     ]
#
#     operations = [
#         migrations.RenameModel(
#             old_name='Series_list',
#             new_name='Serial',
#         ),
#     ]
# Generated by Django 5.0.6 on 2024-06-13 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Series',
            new_name='Serial',
        ),
    ]
