# Generated by Django 5.0.6 on 2024-06-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comentariu_gen_serial_tara_delete_newserieslistname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100000)),
            ],
        ),
    ]
